//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VandeCraenAnton_b1._2_DM_Project_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LiquipediaEntities : DbContext
    {
        public LiquipediaEntities()
            : base("name=LiquipediaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Regio> Regio { get; set; }
        public virtual DbSet<Speler> Speler { get; set; }
        public virtual DbSet<Team> Team { get; set; }
        public virtual DbSet<Transfer> Transfer { get; set; }
    }
}
