//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VandeCraenAnton_b1._2_DM_Project_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfer
    {
        public int id { get; set; }
        public string vorigTeam { get; set; }
        public string nieuwTeam { get; set; }
        public System.DateTime datum { get; set; }
        public int spelerID { get; set; }
        public int teamID { get; set; }
    
        public virtual Speler Speler { get; set; }
        public virtual Team Team { get; set; }
    }
}
